#include "p18f4550.inc"
    LIST p=18F4550
    INCLUDE "CLOCK.inc"		    ;Archivo en el que se configuran los fusibles del PIC18F4550
    CODE 0X00
    
    ORG 0X00
   BRA	INICIO
    ORG 0X08
    BRA	    INT_HIGH
    ORG	0X18
    BRA	    INT_LOW
    
INICIO:
    
    MOVLW   B'01010011'		    ;Se carga el valor en binario 01010011 al registro W
    MOVWF   OSCCON,ACCESS	    ;Se le carga lo que hay en el registro W
   
    CLRF   TRISB,ACCESS
    CLRF    TRISD,ACCESS
    CLRF    TRISC,ACCESS
    CLRF    LATD,ACCESS
    CLRF    LATB,ACCESS
    CLRF    LATC,ACCESS
    
    SETF    TRISA,ACCESS
INI: 
    CLRF    ADCON1,ACCESS
    CLRF    ADCON0,ACCESS
    MOVLW   B'00010101'
    MOVWF   ADCON2,ACCESS
    BSF	    RCON,7,ACCESS
    BCF	    PIR1,6,ACCESS
    BSF	    PIE1,6,ACCESS
    BSF	    INTCON,7,ACCESS
    BSF	    ADCON0,0,ACCESS
   BSF	    ADCON0,1,ACCESS
LOOP:
    BRA	    LOOP
    
INT_LOW:
	BCF	PIR1,6,ACCESS
	RETFIE	1
INT_HIGH:
	BCF	ADCON0,0,ACCESS
	BCF	PIR1,6,ACCESS
	
	
	MOVLW   0XFF
	MOVWF   PR2,ACCESS
	MOVF    ADRESH,W,ACCESS
	;MOVLW   0XFF
	MOVWF   CCPR1L,ACCESS

	MOVF    ADRESL,W,ACCESS
	RRNCF   W,W,ACCESS
	RRNCF   W,W,ACCESS
	MOVWF   CCP1CON,ACCESS
	
	;MOVLW   B'00111100'
	;MOVWF   CCP1CON,ACCESS

	BSF	CCP1CON,2,ACCESS
	BSF     CCP1CON,3,ACCESS

	BSF    T2CON,2,ACCESS

	BSF    ADCON0,0,ACCESS
	BSF	    ADCON0,1,ACCESS
	RETFIE	1
    END